[package]
name = "forge-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
forge-core = { path = "../forge-core" }

serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
